### ISSUE TITLE
Module not found: Can't resolve

### ISSUE THREAD

**Issue by HamedFathi** [cypress-io/cypress-webpack-preprocessor#28] opened 2018-10-06 08:16 UTC
- Operating System: Win 7 / 10
- Cypress Version: latest
- Browser Version: latest

### Is this a Feature or Bug?
Bug

### Current behavior:

```bash
./cypress/integration/simple/spec.ts
Module not found: Error: Can't resolve './test' in 'C:\Users\...\cypress\integration\simple'
resolve './test' in 'C:\Users\...\cypress\integration\simple'
  using description file: C:\Users\...\package.json (relative path: ./cypress/integration/simple)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: C:\Users\...\package.json (relative path: ./cypress/integration/simple/test)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\...\cypress\integration\simple\test doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\...\cypress\integration\simple\test.wasm doesn't exist
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\...\cypress\integration\simple\test.mjs doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\...\cypress\integration\simple\test.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\...\cypress\integration\simple\test.json doesn't exist
      as directory
        C:\Users\...\cypress\integration\simple\test doesn't exist
[C:\Users\...\cypress\integration\simple\test]
[C:\Users\...\cypress\integration\simple\test.wasm]
[C:\Users\...\cypress\integration\simple\test.mjs]
[C:\Users\...\cypress\integration\simple\test.js]
[C:\Users\...\cypress\integration\simple\test.json]
 @ ./cypress/integration/simple/spec.ts 3:0-30 8:32-36
```

### Desired behavior:
It should work with imports.

### How to reproduce:

It is so simple :)

### Additional Info (images, stack traces, etc)

```ts
/// <reference types="cypress" />
import expect from "expect";
import { Test } from "./test";
describe('My First Test', function () {
  it('get Google site title"', function () {
    cy.visit('https://www.google.com/');

    cy.title().should('eq', new Test().message)
  })
})

export class Test {
  message = "Google";
}
```
![image](https://user-images.githubusercontent.com/8418700/46569127-73fe7e80-c95d-11e8-88f3-0c5c183bd42d.png)

**Comment by mkoczorowski** [comment] 2019-03-26 21:20
I have the same problem :/

**Comment by mpahuja** [comment] 2019-08-30 07:58
This issue is reproducible using the default config as mentioned in the Readme:
```
const webpack = require('@cypress/webpack-preprocessor')

module.exports = (on) => {
  on('file:preprocessor', webpack())
}
```

Even though the error `Field 'browser' doesn't contain a valid alias configuration
` can be resolved using the following config:

```
module.exports = (on) => {
  const options = {
    webpackOptions: {
      resolve: {
        extensions: ['.ts', '.tsx', '.js'],
      },
      module: {
        rules: [
          {
            test: /\.tsx?$/,
            exclude: [/node_modules/],
            use: [{
              loader: 'babel-loader',
              options: {
                presets: ['@babel/preset-env'],
              },
            }],
          },
        ],
      },
    }
  }

  on('file:preprocessor', webpack(options));
};
```
I am still have issues this preprocessor transpiling the code correctly. Any help on this is much appreciated. I feel there is some nuance I am missing somewhere.

**Comment by Bkucera** [comment] 2019-08-30 18:26
@mpahuja babel-env doesn't transpile typescript files. Please add this preset as well https://babeljs.io/docs/en/babel-preset-typescript

This plugin doesn't transpile typescript for you by default, you need to properly configure babel. Closing since this isn't an issue with the preprocessor

**Closed by Bkucera** 2019-08-30 18:26 UTC

**Comment by hardikrana437** [comment] 2020-07-11 09:46
I am facing same problem, my webpackconfig.js file:

```
module.exports = {
  resolve: {
    extensions: [".ts", ".js"]
  },
  node: { fs: "empty", child_process: "empty", readline: "empty" },
  module: {
    rules: [
      {
        test: /\.ts$/,
        exclude: [/node_modules/],
        use: [
          {
            loader: "ts-loader"
          }
        ]
      },
      {
        test: /\.feature$/,
        use: [
          {
            loader: "cypress-cucumber-preprocessor/loader"
          }
        ]
      }
    ]
  }
};
```
