### ISSUE TITLE
When your file has an error cypress closes the browser

### ISSUE THREAD

**Issue by philjones88** [cypress-io/cypress-webpack-preprocessor#26] opened 2018-10-03 09:22 UTC
### Current behavior:

On a webpack error, cypress closes the browser with the error, you then have to manually reopen the browser after fixing the file.

### Desired behavior:

Not close the browser. Don't run the test. Show me the error in the browser.

### How to reproduce:

Get some working typescript tests. Enter some gibberish / breaking changes and boom. Cypress closes the browser with the error. You then have to fix it. Re-open browser.

e.g.

![image](https://user-images.githubusercontent.com/677167/46401887-2af8c100-c6f6-11e8-91a8-c9c48c0483be.png)

### Additional Info (images, stack traces, etc)

Using the sample from https://github.com/cypress-io/cypress-webpack-preprocessor#usage

- Operating System: MacOS Mojava
- Cypress Version: 3.1.0
- Browser Version: Chrome 69

**Comment by chrisbreiding** [comment] 2018-10-12 13:21
Can you post the configuration you're using? TypeScript is not part of the sample usage.

**Comment by philjones88** [comment] 2018-10-12 13:29
We followed as per the original issue https://github.com/cypress-io/cypress-webpack-preprocessor#usage

cypress/plugins/index.js
```
const webpack = require('@cypress/webpack-preprocessor');

module.exports = (on) => {
  const options = {
    webpackOptions: require('../../webpack.config'),
  };

  on('file:preprocessor', webpack(options));
};

```
cypress.json
```
{
  "projectId": "<super secret stuff>",
  "baseUrl": "http://localhost",
  "supportFile": "cypress/support/index.ts",
  "pluginFolder": "cypress/plugins/index.js",
  "fixturesFolder": "cypress/fixtures",
  "integrationFolder": "cypress/suites",
  "video": true,
  "videosFolder": "videos",
  "screenshotsFolder": "screenshots",
  "chromeWebSecurity": false,
  "numTestsKeptInMemory": 5
}

```

**Comment by chrisbreiding** [comment] 2018-10-12 13:34
I see, but I'll need your webpack config to reproduce.

**Comment by philjones88** [comment] 2018-10-12 13:35
```const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');

module.exports = {
  resolve: {
    extensions: ['.ts', '.js'],
    plugins: [
      new TsconfigPathsPlugin({ configFile: "./tsconfig.json" })
    ]
  },
  devtool: 'source-map',
  module: {
    rules: [
      {
        test: /\.ts$/,
        exclude: [/node_modules/],
        use: [{
          loader: 'ts-loader',
        }],
      },
    ],
  },

}```

**Comment by dongwoo-kim** [comment] 2019-05-18 05:08
Any updates on this issue? I'm having an exact same issue now, but can't figure out how to solve it.

**Comment by Bkucera** [comment] 2019-11-13 16:55
duplicate of #58

**Closed by Bkucera** 2019-11-13 16:55 UTC
